Lection 4
js-tasks-ru/htmlcss-20240614_waira pull request #6
Opened 2024-09-20 09:40 UTC by goodprofy

<img width="381" alt="image" src="https://github.com/user-attachments/assets/ad956adf-8d9e-4b45-90b8-8e33af2370d7">

Как элегантно сделать Custom form elements?

<img width="360" alt="image" src="https://github.com/user-attachments/assets/0e561f04-b788-410f-87e2-c1ccc3bc0b6d">

<img width="378" alt="image" src="https://github.com/user-attachments/assets/eefca500-c395-45ef-8853-da95fea355db">

Чтобы было красиво нужно добавлять стили через container queries или тоже есть какое-то решение?

2024-09-20 09:40 UTC, jsru-1 commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2024-09-22 12:14 UTC, GSemikozov requested changes

2024-09-22 12:14 UTC, GSemikozov commented on assets/css/main.css
> +@media screen and (width >= 600px) {
везде лучше поменять на `(min-width: 600px)`

2024-09-22 12:14 UTC, GSemikozov commented on components/footer.css
> +  padding: 36px 16px 68px;
по краям точно нужны? или эту проблему на мобилке должен решать контейнер?

2024-09-22 12:14 UTC, GSemikozov commented on components/header.css
> +  padding: 16px 16px 69px;
см выше

2024-09-22 12:14 UTC, GSemikozov commented on pages/template.html
> +  <body class="page page_internal page_grid">
если internal, то в общем-то и grid?

2024-09-24 13:54 UTC, goodprofy commented on assets/css/main.css
> +@media screen and (width >= 600px) {
Поменял. Stylelint по-умолчанию приводит к знакам.

2024-09-24 13:57 UTC, goodprofy commented on components/footer.css
> +  padding: 36px 16px 68px;
Нужны. Не стал делать это в контейнере, как-то странно что один управляет отступами сверху, а другой отступами по бокам.
А правильно как?

2024-09-24 13:58 UTC, goodprofy commented on components/header.css
> +  padding: 16px 16px 69px;
Та же история

2024-09-24 14:00 UTC, jsru-1 commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2024-09-26 16:50 UTC, GSemikozov commented on components/footer.css
> +  padding: 36px 16px 68px;
в случае с контейнером - как раз абсолютно ОК и консистентно по всему сайту

2024-09-29 07:15 UTC, jsru-1 commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2024-09-29 07:16 UTC, goodprofy commented on components/header.css
> +  padding: 16px 16px 69px;
И в preview поправил

2024-09-29 07:20 UTC, GSemikozov approved these changes

2024-09-29 07:20 UTC, merged